@startuml phone_vm
interface IRouter
interface IStorage
interface IPhoneViewModel
interface IAuthAPI
class PhoneViewModel
class SomeManager

PhoneViewModel -up-> IAuthAPI : use
PhoneViewModel -up-|> IPhoneViewModel
PhoneViewModel -up-> IStorage : use
SomeManager -up-> PhoneViewModel : create
IRouter -down-> IPhoneViewModel : use
@enduml