@startuml phone_vm
interface IRouter
interface IStorage
interface IPhoneVM
interface IAuthAPI
class PhoneViewModel
class PhoneOp

PhoneViewModel -|> IPhoneVM
PhoneViewModel -up-> IAuthAPI : use
PhoneViewModel -up-> IStorage : use
PhoneOp -up-> PhoneViewModel : create
IRouter -down-> IPhoneVM : use
@enduml